# Generated by pkgs/therock/scripts/update-source-tree.py; do not edit by hand.
{ inputs }:
{
  "gfx1151" = {
    version = "7.15";
    root = inputs."therock-src-7-15-gfx1151-root";
    submodules = [
      {
        path = "rocm-libraries";
        source = inputs."therock-src-7-15-gfx1151-rocm-libraries-36c771f3";
      }
      {
        path = "rocm-systems";
        source = inputs."therock-src-7-15-gfx1151-rocm-systems-9c0ec3e9";
      }
      {
        path = "base/half";
        source = inputs."therock-src-7-15-gfx1151-base-half-011b45bd";
      }
      {
        path = "base/rocm-cmake";
        source = inputs."therock-src-7-15-gfx1151-base-rocm-cmake-ec512d84";
      }
      {
        path = "compiler/amd-llvm";
        source = inputs."therock-src-7-15-gfx1151-compiler-amd-llvm-1e702164";
      }
      {
        path = "compiler/hipify";
        source = inputs."therock-src-7-15-gfx1151-compiler-hipify-ea979a85";
      }
      {
        path = "compiler/spirv-llvm-translator";
        source = inputs."therock-src-7-15-gfx1151-compiler-spirv-llvm-translator-b9250448";
      }
      {
        path = "math-libs/libhipcxx";
        source = inputs."therock-src-7-15-gfx1151-math-libs-libhipcxx-10b48ff4";
      }
      {
        path = "debug-tools/rocgdb/source";
        source = inputs."therock-src-7-15-gfx1151-debug-tools-rocgdb-source-e3322990";
      }
      {
        path = "third-party/sysdeps/linux/amd-mesa/mesa-fork";
        source = inputs."therock-src-7-15-gfx1151-third-party-sysdeps-linux-amd-mesa-mesa-fork-a692c85c";
      }
    ];
  };
}
