{
  description = "Strix Halo NixOS configuration and tools";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    nix-ai-tools = {
      url = "github:numtide/nix-ai-tools";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    ec-su-axb35 = {
      url = "github:cmetz/ec-su_axb35-linux";
      flake = false;
    };

    llama-cpp-master = {
      url = "github:ggml-org/llama.cpp";
      flake = false;
    };

    llama-cpp-spacemit = {
      url = "github:spacemit-com/llama.cpp/v0.1.5";
      flake = false;
    };

    spine-triton = {
      url = "git+https://github.com/spacemit-com/spine-triton.git?ref=refs/tags/0.5.5&submodules=1";
      flake = false;
    };

    fastflowlm = {
      url = "github:FastFlowLM/FastFlowLM";
      flake = false;
    };

    ds4 = {
      url = "github:antirez/ds4";
      flake = false;
    };

    ds4-hip = {
      url = "github:ejpir/ds4-hip/rocm-upstream-shape-cyberneurova";
      flake = false;
    };

    vllm-src = {
      url = "github:vllm-project/vllm/v0.25.1";
      flake = false;
    };

    mlx-src = {
      url = "github:NripeshN/mlx/rocm-support";
      flake = false;
    };

    thunderbolt-ibverbs = {
      url = "github:hellas-ai/thunderbolt-ibverbs";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    xrt-src = {
      url = "git+https://github.com/Xilinx/XRT?ref=XRT-2.21&submodules=1";
      flake = false;
    };

    xdna-driver-src = {
      url = "git+https://github.com/amd/xdna-driver?ref=1.7&submodules=1";
      flake = false;
    };

    # BEGIN generated TheRock source inputs
    # Generated by pkgs/therock/scripts/update-source-tree.py; do not edit by hand.
    "therock-src-7-15-gfx1151-root" = {
      url = "github:ROCm/TheRock/1de3171d00f6de55e9ed517dc6ca6e825d1e4b55";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-libraries-36c771f3" = {
      url = "github:ROCm/rocm-libraries/fa9cdd186b222f6449a6be1710038bdee4faa328";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-systems-9c0ec3e9" = {
      url = "github:ROCm/rocm-systems/8ceab8e581fbd0e191b1a0a56f9e59d8d1ca4e00";
      flake = false;
    };

    "therock-src-7-15-gfx1151-base-half-011b45bd" = {
      url = "github:ROCm/half/207ee58595a64b5c4a70df221f1e6e704b807811";
      flake = false;
    };

    "therock-src-7-15-gfx1151-base-rocm-cmake-ec512d84" = {
      url = "github:ROCm/rocm-cmake/10155d7272ea1bf79f6b5a9dbc339657af1aa372";
      flake = false;
    };

    "therock-src-7-15-gfx1151-compiler-amd-llvm-1e702164" = {
      url = "github:ROCm/llvm-project/92fe31231dd83aedaedd822daa2079ca8a445547";
      flake = false;
    };

    "therock-src-7-15-gfx1151-compiler-hipify-ea979a85" = {
      url = "github:ROCm/HIPIFY/c917282dbc1fe85d3814807a2c77d4288cff112d";
      flake = false;
    };

    "therock-src-7-15-gfx1151-compiler-spirv-llvm-translator-b9250448" = {
      url = "github:ROCm/SPIRV-LLVM-Translator/ddeda6468d45cf1e888a0e81e50bc170756a335b";
      flake = false;
    };

    "therock-src-7-15-gfx1151-math-libs-libhipcxx-10b48ff4" = {
      url = "github:ROCm/libhipcxx/3ea4c70920e0cdd1bab79d1897043090a93372b6";
      flake = false;
    };

    "therock-src-7-15-gfx1151-debug-tools-rocgdb-source-e3322990" = {
      url = "github:ROCm/rocgdb/1b5ded2e8e4239e9dc94b7c77c1b753cc7f68e26";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-abseil-cpp-471579c4" = {
      url = "github:abseil/abseil-cpp/255c84dadd029fd8ad25c5efb5933e47beaa00c7";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-cereal-7f708e93" = {
      url = "github:jrmadsen/cereal/40a30defcb8874270a04836d316502b08904b2bc";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-elfio-cf38c296" = {
      url = "github:serge1/ELFIO/575bfdb12cd90fa8913660295103549f151d116a";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-filesystem-807165f4" = {
      url = "github:gulrak/filesystem/8a2edd6d92ed820521d42c94d179462bf06b5ed3";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-gotcha-10fa2c98" = {
      url = "github:ROCm/GOTCHA/b944da10ff9b3364ef2e4b12e02cb2464e05dd48";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-json-a3f85fd2" = {
      url = "github:nlohmann/json/e41905fcb0938a7502d25ea5242c6b41396e21b0";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-perfetto-9d309359" = {
      url = "github:google/perfetto/eb5ef24c58d13cec289d733d03f0f3f0ed321b12";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-ptl-db721fa0" = {
      url = "github:jrmadsen/PTL/48df41625430d27ce43cf197fd467a8dda87cb45";
      flake = false;
    };

    "therock-src-7-15-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-pybind11-6da66437" = {
      url = "github:pybind/pybind11/914c06fb252b6cc3727d0eedab6736e88a3fcb01";
      flake = false;
    };

    "therock-src-7-15-gfx1151-third-party-sysdeps-linux-amd-mesa-mesa-fork-a692c85c" = {
      url = "github:ROCm/mesa-fork/22abfc06d7cf4c115ca2e368505d75ba4af174b4";
      flake = false;
    };

    # END generated TheRock source inputs
  };

  outputs =
    {
      self,
      nixpkgs,
      ...
    }@inputs:
    let
      inherit (nixpkgs) lib;
      linuxSystems = [ "x86_64-linux" ];
      darwinSystems = [ "aarch64-darwin" ];
      systems = linuxSystems ++ darwinSystems;
      forAllSystems = lib.genAttrs systems;
      inputShortRev =
        input: input.shortRev or (if input ? rev then builtins.substring 0 7 input.rev else "unknown");
      inputVersion = prefix: input: "${prefix}-unstable-${inputShortRev input}";
      unstableInputVersion = input: "unstable-${inputShortRev input}";

      rocmTargetLib = import ./lib/rocm-targets.nix;
      therockTargetConfig = import ./pkgs/therock/targets.nix {
        inherit (rocmTargetLib) mkRocmTarget;
      };
      inherit (therockTargetConfig)
        defaultRocmTarget
        rocmTargets
        ;

      providers = import ./lib/providers.nix { inherit lib; };
      benchLib = import ./lib/bench/lib.nix { inherit lib; };
      therockPythonConfig = import ./pkgs/therock/python-config.nix { inherit lib; };

      defaultTherockSources = {
        rocm = builtins.fromJSON (builtins.readFile ./pkgs/therock/sources/rocm.json);
        pythonWheels = builtins.fromJSON (builtins.readFile ./pkgs/therock/sources/python-wheels.json);
        rocmSourcePins = builtins.fromJSON (builtins.readFile ./pkgs/therock/sources/rocm-source.json);
        rocmSourceTrees = import ./pkgs/therock/sources/source-tree.nix { inherit inputs; };
        rocmThirdParty = builtins.fromJSON (builtins.readFile ./pkgs/therock/sources/rocm-third-party.json);
      };

      thunderboltIbverbsOverlay = inputs.thunderbolt-ibverbs.overlays.default;
      spacemitK3Overlay = import ./overlays/spacemit-k3.nix {
        inherit inputs inputVersion;
      };

      # Re-export thunderbolt-ibverbs flake packages under the names
      # downstream callers expect. The upstream package set uses
      # unprefixed names (`bench-tools`, `perftest`); we prefix them so
      # the global package namespace doesn't collide. Also alias
      # `rdma-core` to the USB4-enabled build on Linux.
      thunderboltRenamesOverlay =
        _: prev:
        let
          tbPkgs = inputs.thunderbolt-ibverbs.packages.${prev.stdenv.hostPlatform.system};
        in
        {
          thunderbolt-ibverbs-bench-tools = tbPkgs.bench-tools;
          thunderbolt-ibverbs-perftest = tbPkgs.perftest;
        }
        // lib.optionalAttrs prev.stdenv.isLinux {
          inherit (tbPkgs)
            linux-thunderbolt
            linux-thunderbolt-dev
            linux-thunderbolt-modules
            rdma-core-usb4
            thunderbolt-ibverbs
            thunderbolt-ibverbs-linux-thunderbolt
            ;
          rdma-core = tbPkgs.rdma-core-usb4;
        };

      # Compose the overlay list for a given (rocmTarget, providers, cpu).
      # The active rocm/python providers feed the locally-defined-packages
      # overlay through `final.rocmPackages` / `final.python3Packages`.
      mkOverlays =
        {
          rocmTarget,
          rocmProvider ? "therock-bin",
          pythonProvider ? "therock-wheels",
          cpu ? null,
        }:
        let
          suffix = rocmTarget.packageSuffix;
          hasTherockRocmSource = lib.hasAttrByPath [
            "rocm"
            "linux"
            suffix
          ] defaultTherockSources;
          hasTherockPythonSource = lib.hasAttrByPath [
            "pythonWheels"
            "targets"
            suffix
          ] defaultTherockSources;
          enableTherockVllm =
            rocmProvider != "nixpkgs"
            && pythonProvider == "therock-wheels"
            && hasTherockRocmSource
            && hasTherockPythonSource;
        in
        [
          thunderboltIbverbsOverlay
          thunderboltRenamesOverlay
          (import ./overlays/rocm.nix {
            inherit lib therockPythonConfig;
            provider = rocmProvider;
            inherit rocmTarget rocmTargets;
            sources = defaultTherockSources;
          })
          (import ./overlays/python.nix {
            inherit lib therockPythonConfig;
            provider = pythonProvider;
            inherit rocmTarget;
          })
          (import ./overlays/therock-vllm.nix {
            inherit lib therockPythonConfig;
            target = rocmTarget;
            vllmSrc = inputs.vllm-src;
            vllmVersion = "0.25.1";
            enabled = enableTherockVllm;
          })
          (import ./overlays/pkgs.nix {
            inherit
              inputs
              lib
              inputVersion
              rocmTarget
              rocmProvider
              pythonProvider
              ;
            sources = defaultTherockSources;
          })
        ]
        ++ lib.optional (cpu != null) (import ./overlays/mtune.nix { inherit lib cpu; });

      # The parameterised package set. Different `rocmTarget` /
      # `rocmProvider` / `pythonProvider` produce different package sets;
      # the flake's default outputs commit to one combination, the
      # legacyPackages tree exposes the rest per rocmTarget.
      pkgsFor =
        {
          system,
          rocmTarget ? defaultRocmTarget,
          rocmProvider ? "therock-bin",
          pythonProvider ? "therock-wheels",
          cpu ? null,
          cudaSupport ? false,
        }:
        import nixpkgs {
          inherit system;
          config = {
            allowUnfree = true;
          }
          // lib.optionalAttrs cudaSupport {
            cudaSupport = true;
            cudaCapabilities = [ "8.9" ];
          };
          overlays = mkOverlays {
            inherit
              rocmTarget
              rocmProvider
              pythonProvider
              cpu
              ;
          };
        };

      defaultPkgsFor = system: pkgsFor { inherit system; };
      cudaPkgsFor =
        system:
        pkgsFor {
          inherit system;
          cudaSupport = true;
        };

      perSystem = f: forAllSystems (system: f (defaultPkgsFor system));

      mkBenchmarkSuites = import ./lib/bench {
        inherit
          lib
          self
          defaultRocmTarget
          cudaPkgsFor
          benchLib
          ;
      };

      hydraLib = import ./lib/hydra.nix {
        inherit
          lib
          self
          pkgsFor
          defaultRocmTarget
          ;
      };

      mkLiveIsoConfiguration =
        {
          system ? "x86_64-linux",
          extraModules ? [ ],
          specialArgs ? { },
        }:
        nixpkgs.lib.nixosSystem {
          inherit system;
          specialArgs = {
            inherit inputs self;
          }
          // specialArgs;
          modules = [
            ./examples/configuration.nix
          ]
          ++ extraModules;
        };
    in
    {
      lib = {
        inherit
          defaultTherockSources
          mkLiveIsoConfiguration
          ;
        inherit (rocmTargetLib) mkRocmTarget;
        inherit (providers) rocmProviders pythonProviders pythonProviderStubs;
        therockTargets = therockTargetConfig;
        bench = benchLib;

        # Parameterised overlay builders. Power users compose these to
        # build their own package sets; see lib.mkRocmOverlay etc. The
        # flake's `overlays.default` is the composition of all of these
        # against the default rocmTarget + providers.
        mkRocmOverlay =
          args:
          import ./overlays/rocm.nix (
            {
              inherit lib rocmTargets;
              sources = defaultTherockSources;
            }
            // args
          );
        mkPythonOverlay = args: import ./overlays/python.nix ({ inherit lib; } // args);
        mkPkgsOverlay =
          args:
          import ./overlays/pkgs.nix (
            {
              inherit lib inputs inputVersion;
              sources = defaultTherockSources;
            }
            // args
          );
        mkMtuneOverlay = args: import ./overlays/mtune.nix ({ inherit lib; } // args);
      };

      overlays = {
        default = lib.composeManyExtensions (mkOverlays {
          rocmTarget = defaultRocmTarget;
        });
        python = self.lib.mkPythonOverlay {
          provider = "nixpkgs";
        };
        spacemitK3 = spacemitK3Overlay;
      };

      # NixOS modules
      nixosModules = {
        default = _: {
          imports = [
            inputs.thunderbolt-ibverbs.nixosModules.default
          ];
          nixpkgs.overlays = [
            self.overlays.default
          ];
        };
        rpc-server = import ./modules/rpc-server.nix;
        benchmark-executor = import ./modules/benchmark-executor.nix;
        benchmark-runner = import ./modules/benchmark-runner.nix;
        ec-su-axb35 = import ./modules/ec-su-axb35.nix;
        fastflowlm = import ./modules/fastflowlm.nix;
        ryzenadj = import ./modules/ryzenadj.nix;
        tuning = import ./modules/tuning.nix;
        thunderbolt-ibverbs = inputs.thunderbolt-ibverbs.nixosModules.default;
      };

      nixosConfigurations = {
        live-iso = mkLiveIsoConfiguration { };
      };

      darwinModules = {
        benchmark-executor = import ./modules/benchmark-executor.nix;
      };
    }
    // {
      # Per-target pkgs sets. Use to escape-hatch to a non-default rocm
      # target: `nix build .#legacyPackages.x86_64-linux.gfx1103.llama-cpp-rocm`.
      legacyPackages = forAllSystems (
        system:
        lib.listToAttrs (
          map (rocmTarget: {
            name = rocmTarget.packageSuffix;
            value = pkgsFor { inherit system rocmTarget; };
          }) rocmTargets
        )
      );

      benchmarks = perSystem mkBenchmarkSuites;

      packages = perSystem (
        pkgs:
        let
          system = pkgs.stdenv.hostPlatform.system;
          s = defaultRocmTarget.packageSuffix;
          aiTools = inputs.nix-ai-tools.packages.${system};
          cudaPkgs = cudaPkgsFor system;
          packageRuntimeEnv = import ./lib/runtime-env.nix { inherit lib; };
          inherit (packageRuntimeEnv) wrapRuntimeEnv;
          jacclPackage = pkgs.callPackage ./pkgs/jaccl (
            {
              inherit (inputs) mlx-src;
            }
            // lib.optionalAttrs pkgs.stdenv.isLinux {
              rdma-core = pkgs.rdma-core-usb4;
            }
          );
          mkMlxLm =
            {
              mlxPackage,
              pythonPackages ? pkgs.python3Packages,
            }:
            let
              mlxLm = pythonPackages.mlx-lm.overridePythonAttrs (
                oldAttrs:
                {
                  dependencies = lib.unique (
                    lib.filter (dep: dep.pname or "" != "mlx") (
                      oldAttrs.dependencies or oldAttrs.propagatedBuildInputs or [ ]
                    )
                    ++ [
                      mlxPackage
                    ]
                    ++ lib.optional pkgs.stdenv.isLinux pythonPackages.sentencepiece
                  );
                  meta = (oldAttrs.meta or { }) // {
                    mainProgram = "mlx_lm";
                  };
                }
                // lib.optionalAttrs pkgs.stdenv.isLinux {
                  doCheck = false;
                  doInstallCheck = false;
                  dontCheckRuntimeDeps = true;
                  pythonImportsCheck = [ "mlx_lm" ];
                }
              );
            in
            if mlxPackage ? passthru && mlxPackage.passthru ? rocmRuntimeEnv then
              wrapRuntimeEnv {
                inherit pkgs;
                package = mlxLm;
                name = "mlx-lm-rocm-runtime";
                env = mlxPackage.passthru.rocmRuntimeEnv;
              }
            else
              mlxLm;

          availableDerivationNames =
            names: lib.filter (name: builtins.hasAttr name pkgs && lib.isDerivation pkgs.${name}) names;

          linuxLocalPackageNames = [
            "ds4-rocm"
            "ec-su-axb35"
            "ec-su-axb35-monitor"
            "fastflowlm"
            "llama-cpp-master-rocm"
            "llama-cpp-master-vulkan"
            "llama-cpp-rocm"
            "llama-cpp-vulkan"
            "mlx-rocm"
            "sglang-rocm"
            "strix-halo-mes-firmware"
            "therock-amdsmi"
            "therock-python"
            "therock-python-wheels"
            "therock-rocm"
            "therock-rocm-env"
            "tokenizers-cpp"
            "torch-rocm"
            "vllm-rocm"
            "xrt"
            "xrt-amdxdna"
          ];

          genericPackages = {
            default = pkgs.llama-cpp;
            pi-wrap = pkgs.callPackage ./pkgs/pi-wrap {
              inherit (aiTools) pi;
            };
            inherit (aiTools) pi;
            inherit (pkgs)
              llama-cpp
              llama-cpp-master
              thunderbolt-ibverbs-bench-tools
              thunderbolt-ibverbs-perftest
              ;
            jaccl = jacclPackage;
          };

          spacemitK3Packages = lib.optionalAttrs (system == "x86_64-linux") (
            let
              spacemitPkgs = import nixpkgs {
                inherit system;
                config.allowUnfree = true;
                overlays = [ spacemitK3Overlay ];
              };
            in
            {
              inherit (spacemitPkgs)
                llama-cpp-spacemit
                spacemit-k3-runtime
                spacemit-k3-spine-mlir
                spacemit-k3-toolchain
                spine-triton-source
                ;
            }
          );

          # Two-host vLLM transport-matrix driver. The driver only needs the
          # vLLM closure to expose both `vllm` and `ray`, so join the default
          # ROCm vLLM package with ray rather than baking ray into vllm-rocm.
          vllmPairBenchEnv = pkgs.symlinkJoin {
            name = "vllm-rocm-${s}-ray-env";
            paths = [
              pkgs.vllm-rocm
              pkgs.${therockPythonConfig.packagesAttr}.ray
            ];
          };

          linuxPackages =
            let
              mlxRocm = pkgs.mlx-rocm;
              mlxLmRocm = mkMlxLm { mlxPackage = mlxRocm; };
            in
            lib.genAttrs (availableDerivationNames linuxLocalPackageNames) (name: pkgs.${name})
            // {
              inherit (pkgs)
                linux-thunderbolt
                linux-thunderbolt-dev
                linux-thunderbolt-modules
                rdma-core-usb4
                thunderbolt-ibverbs
                thunderbolt-ibverbs-linux-thunderbolt
                ;
              inherit (cudaPkgs) llama-cpp-cuda llama-cpp-master-cuda;
              live-iso = self.nixosConfigurations.live-iso.config.system.build.isoImage;
              mlx = mlxRocm;
              mlx-lm = mlxLmRocm;
              "strix-halo-vllm-pair-bench-${s}" = pkgs.callPackage ./pkgs/strix-halo-vllm-pair-bench {
                vllmPackage = vllmPairBenchEnv;
                packageSuffix = s;
              };
            };

          darwinPackages =
            let
              # Python 3.14 currently aborts in libffi while building MLX's
              # macOS wheel. Keep the complete Metal stack on Python 3.13.
              mlxPythonPackages = pkgs.python313Packages;
              mlxNanobind = mlxPythonPackages.callPackage ./pkgs/mlx/nanobind-2_13.nix { };
              mlxMetalBackend = mlxPythonPackages.callPackage ./pkgs/mlx/metal.nix {
                inherit (inputs) mlx-src;
                nanobind = mlxNanobind;
                pname = "mlx-metal";
                buildStage = 2;
              };
              mlxMetal = mlxPythonPackages.callPackage ./pkgs/mlx/metal.nix {
                inherit (inputs) mlx-src;
                nanobind = mlxNanobind;
                pname = "mlx";
                buildStage = 1;
                backendPackage = mlxMetalBackend;
              };
              mlxLm = mkMlxLm {
                mlxPackage = mlxMetal;
                pythonPackages = mlxPythonPackages;
              };
            in
            {
              ds4 = pkgs.callPackage ./pkgs/ds4 {
                src = inputs.ds4;
                version = unstableInputVersion inputs.ds4;
              };
              inherit (pkgs) llama-cpp-master-rdma;
              mlx = mlxMetal;
              mlx-lm = mlxLm;
              mlx-metal = mlxMetalBackend;
            };
        in
        genericPackages
        // spacemitK3Packages
        // lib.optionalAttrs pkgs.stdenv.isLinux linuxPackages
        // lib.optionalAttrs pkgs.stdenv.isDarwin darwinPackages
      );

      apps = perSystem (
        pkgs:
        let
          system = pkgs.stdenv.hostPlatform.system;
          s = defaultRocmTarget.packageSuffix;
          runtimeEnv = import ./lib/runtime-env.nix { inherit lib; };
          inherit (runtimeEnv) mkApp wrapRuntimeEnv;

          # Positional helper. `mkApp` is the structured form; this is
          # the inline version for entries where the structure adds no
          # information.
          ap =
            package: binary: description:
            mkApp { inherit package binary description; };

          # Wrap the default-target llama-cpp-rocm with the target's HSA
          # env once; the -rocm apps point at that wrapped package. For
          # non-default targets, consumers use legacyPackages directly.
          llamaRocmRuntime = wrapRuntimeEnv {
            inherit pkgs;
            package = pkgs.llama-cpp-rocm;
            name = "llama-cpp-rocm-${s}-runtime";
            env = lib.optionalAttrs (defaultRocmTarget.hsaOverride != null) {
              HSA_OVERRIDE_GFX_VERSION = defaultRocmTarget.hsaOverride;
            };
          };

          genericApps = {
            pi-wrap =
              ap self.packages.${system}.pi-wrap "pi-wrap"
                "Run pi with provider settings from environment";
            llama-cli = ap pkgs.llama-cpp "llama-cli" "Run llama-cli";
            llama-server = ap pkgs.llama-cpp "llama-server" "Run llama-server";
            llama-rpc-server = ap pkgs.llama-cpp "llama-rpc-server" "Run the llama.cpp RPC server";
            llama-cli-master = ap pkgs.llama-cpp-master "llama-cli" "Run llama-cli from llama.cpp HEAD";
            llama-server-master =
              ap pkgs.llama-cpp-master "llama-server"
                "Run llama-server from llama.cpp HEAD";
            llama-rpc-server-master =
              ap pkgs.llama-cpp-master "llama-rpc-server"
                "Run the llama.cpp HEAD RPC server";
          };

          linuxApps = {
            llama-cli-rocm =
              ap llamaRocmRuntime "llama-cli"
                "Run llama-cli with ROCm (default target ${defaultRocmTarget.description})";
            llama-server-rocm =
              ap llamaRocmRuntime "llama-server"
                "Run llama-server with ROCm (default target ${defaultRocmTarget.description})";
            llama-rpc-server-rocm =
              ap llamaRocmRuntime "llama-rpc-server"
                "Run the llama.cpp RPC server with ROCm (default target ${defaultRocmTarget.description})";
            flm = ap pkgs.fastflowlm "flm" "Run the FastFlowLM CLI on AMD Ryzen AI NPUs";
            "strix-halo-vllm-pair-bench-${s}" =
              ap self.packages.${system}."strix-halo-vllm-pair-bench-${s}" "strix-halo-vllm-pair-bench-${s}"
                "Run vLLM transport-matrix scenarios across a Strix Halo pair";
            therock-rocm-env =
              ap pkgs.therock-rocm-env "therock-rocm-${s}-env"
                "Run a command in the pinned TheRock ROCm ${s} environment";
            therock-python =
              ap pkgs.therock-python "therock-python"
                "Run Python in the pinned TheRock ROCm/PyTorch wheel environment";
            therock-python-env =
              ap pkgs.therock-python "therock-python-env"
                "Run a command in the pinned TheRock ROCm/PyTorch wheel environment";
            mlx-lm = ap self.packages.${system}.mlx-lm "mlx_lm" "Run the MLX LM CLI with ROCm";
            mlx-lm-generate =
              ap self.packages.${system}.mlx-lm "mlx_lm.generate"
                "Generate text with MLX LM on ROCm";
            mlx-lm-chat = ap self.packages.${system}.mlx-lm "mlx_lm.chat" "Run the MLX LM chat CLI on ROCm";
            mlx-lm-server =
              ap self.packages.${system}.mlx-lm "mlx_lm.server"
                "Run the MLX LM HTTP server on ROCm";
            sglang-rocm = ap pkgs.sglang-rocm "sglang" "Run SGLang with ROCm";

            live-iso-vm =
              let
                iso = self.packages.${system}.live-iso;
              in
              {
                type = "app";
                program = toString (
                  pkgs.writeShellScript "live-iso-vm" ''
                    set -euo pipefail
                    iso_file=$(echo ${iso}/iso/*.iso)
                    if [ ! -f "$iso_file" ]; then
                      echo "live ISO not found under ${iso}/iso" >&2
                      exit 1
                    fi
                    kvm_args=()
                    if [ -w /dev/kvm ]; then
                      kvm_args+=(-enable-kvm -cpu host)
                    fi
                    exec ${pkgs.qemu}/bin/qemu-system-x86_64 \
                      "''${kvm_args[@]}" \
                      -m ''${LIVE_ISO_MEM:-4G} \
                      -smp ''${LIVE_ISO_CPUS:-4} \
                      -cdrom "$iso_file" \
                      -boot d \
                      "$@"
                  ''
                );
                meta.description = "Boot the strix-halo live ISO in QEMU (override LIVE_ISO_MEM, LIVE_ISO_CPUS)";
              };
          };

          darwinApps =
            let
              ds4 = ap self.packages.${system}.ds4;
              mlxLm = self.packages.${system}.mlx-lm;
            in
            {
              ds4 = ds4 "ds4" "Run DwarfStar 4 with Metal";
              ds4-server = ds4 "ds4-server" "Run the DwarfStar 4 HTTP server with Metal";
              ds4-bench = ds4 "ds4-bench" "Run the DwarfStar 4 benchmark with Metal";
              ds4-eval = ds4 "ds4-eval" "Run DwarfStar 4 eval with Metal";
              ds4-agent = ds4 "ds4-agent" "Run the DwarfStar 4 agent with Metal";
              ds4-download-model = ds4 "ds4-download-model" "Download DS4 DeepSeek V4 Flash GGUF weights";
              llama-cli-master-rdma =
                ap pkgs.llama-cpp-master-rdma "llama-cli"
                  "Run llama-cli from llama.cpp HEAD with Apple RDMA support";
              llama-rpc-server-master-rdma =
                ap pkgs.llama-cpp-master-rdma "llama-rpc-server"
                  "Run the llama.cpp HEAD RPC server with Apple RDMA support";
              mlx-lm = ap mlxLm "mlx_lm" "Run the MLX LM CLI";
              mlx-lm-generate = ap mlxLm "mlx_lm.generate" "Generate text with MLX LM";
              mlx-lm-chat = ap mlxLm "mlx_lm.chat" "Run the MLX LM chat CLI";
              mlx-lm-server = ap mlxLm "mlx_lm.server" "Run the MLX LM HTTP server";
            };
        in
        genericApps
        // lib.optionalAttrs pkgs.stdenv.isLinux linuxApps
        // lib.optionalAttrs pkgs.stdenv.isDarwin darwinApps
      );

      checks = perSystem (
        pkgs:
        lib.optionalAttrs (pkgs.stdenv.hostPlatform.system == "x86_64-linux") (
          let
            system = pkgs.stdenv.hostPlatform.system;
            src = self;
            runSourceCheck =
              name: nativeBuildInputs: command:
              pkgs.runCommandLocal "ci-${name}"
                {
                  inherit nativeBuildInputs;
                  meta.maintainers = with lib.maintainers; [ georgewhewell ];
                }
                ''
                  export HOME="$TMPDIR/home"
                  export XDG_CACHE_HOME="$TMPDIR/cache"
                  mkdir -p "$HOME" "$XDG_CACHE_HOME"
                  cp -R --no-preserve=mode,ownership ${src} "$TMPDIR/src"
                  chmod -R u+rwX "$TMPDIR/src"
                  cd "$TMPDIR/src"
                  ${command}
                  touch "$out"
                '';

            packageSurface =
              let
                plain = builtins.unsafeDiscardStringContext;
              in
              assert
                self.packages.${system}.llama-cpp-rocm.drvPath
                == self.legacyPackages.${system}.gfx1151.llama-cpp-rocm.drvPath;
              assert
                self.packages.${system}.vllm-rocm.drvPath
                == self.legacyPackages.${system}.gfx1151.vllm-rocm.drvPath;
              assert !(self.packages.${system} ? llama-cpp-rocm-gfx1151);
              assert !(self.packages.${system} ? vllm-rocm-therock-gfx1151);
              assert !(self.legacyPackages.${system}.gfx1103 ? ds4-rocm);
              assert !(self.legacyPackages.${system}.gfx1103 ? vllm-rocm);
              pkgs.runCommandLocal "ci-package-surface"
                {
                  meta.maintainers = with lib.maintainers; [ georgewhewell ];
                }
                ''
                  cat > "$out" <<'EOF'
                  default llama-cpp-rocm: ${plain self.packages.${system}.llama-cpp-rocm.drvPath}
                  legacy gfx1151 llama-cpp-rocm: ${plain self.legacyPackages.${system}.gfx1151.llama-cpp-rocm.drvPath}
                  legacy gfx1103 llama-cpp-rocm: ${plain self.legacyPackages.${system}.gfx1103.llama-cpp-rocm.drvPath}
                  default vllm-rocm: ${plain self.packages.${system}.vllm-rocm.drvPath}
                  EOF
                '';

            cudaHostDriverRuntime =
              let
                cudaBenchmark = self.benchmarks.${system}.bench-cuda-rtx4090-llama-cpp-master-device-smoke;
                cudaBenchmarkMetadata = builtins.toJSON (
                  removeAttrs cudaBenchmark.passthru.benchmark [ "command" ]
                );
                runnerConfig =
                  (lib.nixosSystem {
                    inherit system;
                    modules = [
                      self.nixosModules.benchmark-runner
                      (
                        { config, ... }:
                        {
                          nixpkgs.config.allowUnfree = true;
                          boot.kernelParams = [ "iommu=off" ];
                          hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.latest;
                          benchmark.runners.cuda-rtx4090.gpus = [
                            {
                              type = "nvidia";
                              arch = "rtx4090";
                            }
                          ];
                        }
                      )
                    ];
                  }).config;
                runnerMetadata = builtins.toJSON {
                  features = runnerConfig.nix.settings.system-features;
                  sandboxPaths = runnerConfig.nix.settings.extra-sandbox-paths;
                };
              in
              pkgs.runCommandLocal "ci-cuda-host-driver-runtime"
                {
                  nativeBuildInputs = [ pkgs.jq ];
                  meta.maintainers = with lib.maintainers; [ georgewhewell ];
                }
                ''
                  cat > benchmark.json <<'JSON'
                  ${cudaBenchmarkMetadata}
                  JSON

                  cat > runner.json <<'JSON'
                  ${runnerMetadata}
                  JSON

                  jq -e '
                    .env.LD_LIBRARY_PATH == "/run/opengl-driver-lib"
                    and (.requirements.sandboxPaths | index("/run/opengl-driver") != null)
                    and (.requirements.sandboxPaths | index("/run/opengl-driver-lib") != null)
                    and .target.runtimeDriver.libraryPath == "/run/opengl-driver-lib"
                    and (.target.runtimeDriver | has("binPath") | not)
                    and .tool.packageRole == "llama-cpp-master-cuda"
                    and (.packages | index("nvidia-x11") == null)
                  ' benchmark.json

                  jq -e '
                    (.features | index("benchmark") != null)
                    and (.features | index("rtx4090") != null)
                    and (.sandboxPaths | index("/dev/nvidia0?") != null)
                    and (.sandboxPaths | index("/run/opengl-driver") != null)
                    and (.sandboxPaths | index("/run/opengl-driver-lib=/run/opengl-driver/lib") != null)
                    and (.sandboxPaths | map(select(test("^/nix/store/.*nvidia-x11"))) | length) == 1
                    and (.sandboxPaths | map(select(test("benchmark-nvidia-driver"))) | length) == 0
                  ' runner.json

                  touch "$out"
                '';

            # Build the pair-bench driver against stub vLLM/RDMA/GCC closures so
            # CI validates the wrapper, matrix script, and client without the
            # heavy ROCm closure or a real two-host lab.
            fakeVllmEnv = pkgs.runCommandLocal "ci-fake-vllm-env" { } ''
              mkdir -p "$out/bin"
              for exe in vllm ray python python3; do
                printf '%s\n' \
                  '#!/bin/sh' \
                  'echo "fake $(basename "$0") $*"' \
                  > "$out/bin/$exe"
                chmod +x "$out/bin/$exe"
              done
            '';
            fakeRdmaCore = pkgs.runCommandLocal "ci-fake-rdma-core" { } ''
              mkdir -p "$out/bin" "$out/lib"
              touch "$out/lib/libibverbs.so.1"
              printf '%s\n' \
                '#!/bin/sh' \
                'echo "device"' \
                'echo "------"' \
                'echo "usb4_rdma0"' \
                > "$out/bin/ibv_devices"
              chmod +x "$out/bin/ibv_devices"
            '';
            fakeGcc = pkgs.runCommandLocal "ci-fake-gcc-prefix" { } ''
              mkdir -p "$out/bin"
              printf '%s\n' \
                '#!/bin/sh' \
                'echo "fake gcc $*"' \
                > "$out/bin/gcc"
              chmod +x "$out/bin/gcc"
            '';
            vllmPairBenchCheckPackage = pkgs.callPackage ./pkgs/strix-halo-vllm-pair-bench {
              gcc = fakeGcc;
              rdma-core = fakeRdmaCore;
              vllmPackage = fakeVllmEnv;
              packageSuffix = "ci";
            };
          in
          {
            deadnix = runSourceCheck "deadnix" [ pkgs.deadnix ] "deadnix --fail .";
            statix = runSourceCheck "statix" [ pkgs.statix ] "statix check .";
            nixfmt = runSourceCheck "nixfmt" [
              pkgs.nixfmt-tree
            ] "treefmt --tree-root . --walk filesystem --fail-on-change .";
            cuda-host-driver-runtime = cudaHostDriverRuntime;
            package-surface = packageSurface;
            vllm-pair-bench-dry-run =
              pkgs.runCommandLocal "ci-vllm-pair-bench-dry-run"
                {
                  nativeBuildInputs = [
                    pkgs.gnugrep
                    pkgs.python3
                    vllmPairBenchCheckPackage
                  ];
                  meta.maintainers = with lib.maintainers; [ georgewhewell ];
                }
                ''
                  bash -n ${./lib/bench/vllm-transport-matrix.sh}
                  python3 -m py_compile ${./lib/bench/vllm-stream-client.py}
                  strix-halo-vllm-pair-bench-ci --scenario qwen-peak --dry-run | tee "$out"
                  grep -q "dry-run: not invoking" "$out"
                '';
          }
        )
      );

      devShells = perSystem (pkgs: {
        default = pkgs.mkShell {
          packages =
            (with pkgs; [
              deadnix
              nix-fast-build
              nixfmt-tree
              statix
            ])
            ++ (with inputs.nix-ai-tools.packages.${pkgs.stdenv.hostPlatform.system}; [
              pi
            ])
            ++ [
              self.packages.${pkgs.stdenv.hostPlatform.system}.pi-wrap
            ]
            ++ lib.optionals pkgs.stdenv.isLinux [
              (pkgs.python3.withPackages (
                ps: with ps; [
                  numpy
                  pandas
                  plotly
                ]
              ))
            ];
        };
      });

      formatter = perSystem (pkgs: pkgs.nixfmt-tree);

      hydraBenchmarkJobs = perSystem hydraLib.mkBenchmarkJobs;

      hydraJobs = perSystem hydraLib.mkJobs;

    };
}
