{
  description = "Strix Halo NixOS configuration and tools";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    ec-su-axb35 = {
      url = "github:cmetz/ec-su_axb35-linux";
      flake = false;
    };

    llama-cpp-master = {
      url = "github:ggml-org/llama.cpp";
      flake = false;
    };

    fastflowlm = {
      url = "github:FastFlowLM/FastFlowLM";
      flake = false;
    };

    ds4 = {
      url = "github:antirez/ds4";
      flake = false;
    };

    ds4-hip = {
      url = "github:ejpir/ds4-hip/rocm-upstream-shape-cyberneurova";
      flake = false;
    };

    vllm-src = {
      url = "github:vllm-project/vllm/v0.21.0";
      flake = false;
    };

    mlx-src = {
      url = "github:ml-explore/mlx/e8ebdebeeb655feaa85a51f6b24ece5b6d5518d1";
      flake = false;
    };

    thunderbolt-ibverbs = {
      url = "git+ssh://git@github.com/hellas-ai/thunderbolt-ibverbs.git";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    xrt-src = {
      url = "git+https://github.com/Xilinx/XRT?ref=XRT-2.21&submodules=1";
      flake = false;
    };

    xdna-driver-src = {
      url = "git+https://github.com/amd/xdna-driver?ref=1.7&submodules=1";
      flake = false;
    };

    # BEGIN generated TheRock source inputs
    # Generated by pkgs/therock/scripts/update-source-tree.py; do not edit by hand.
    "therock-src-7-13-gfx1151-root" = {
      url = "github:ROCm/TheRock/6d2136cd12be28c6251eb38c700e980c8c2f8cf6";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-libraries-36c771f3" = {
      url = "github:ROCm/rocm-libraries/f664f44c90ae22e860738f8c9793a019eb1975e1";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-9c0ec3e9" = {
      url = "github:ROCm/rocm-systems/79e85e1468f96a867108043c953e9547c13b4c5e";
      flake = false;
    };

    "therock-src-7-13-gfx1151-base-half-011b45bd" = {
      url = "github:ROCm/half/207ee58595a64b5c4a70df221f1e6e704b807811";
      flake = false;
    };

    "therock-src-7-13-gfx1151-base-rocm-cmake-ec512d84" = {
      url = "github:ROCm/rocm-cmake/10155d7272ea1bf79f6b5a9dbc339657af1aa372";
      flake = false;
    };

    "therock-src-7-13-gfx1151-compiler-amd-llvm-1e702164" = {
      url = "github:ROCm/llvm-project/43215c73116c407735c85a180d174f718798c328";
      flake = false;
    };

    "therock-src-7-13-gfx1151-compiler-hipify-ea979a85" = {
      url = "github:ROCm/HIPIFY/0f3db9c13669d702e12023ae2bfe0882daab63d5";
      flake = false;
    };

    "therock-src-7-13-gfx1151-compiler-spirv-llvm-translator-b9250448" = {
      url = "github:ROCm/SPIRV-LLVM-Translator/aa7c842d4ec5b7015022ae6c6b91a4365bb6b91d";
      flake = false;
    };

    "therock-src-7-13-gfx1151-iree-libs-fusilli-e6b3e4e6" = {
      url = "github:iree-org/fusilli/aeed46fe35604c9f055f35005b95dc7e8f56633e";
      flake = false;
    };

    "therock-src-7-13-gfx1151-iree-libs-iree-89b77fa6" = {
      url = "github:iree-org/iree/192602f8a7680467e608480debdb2ed6062d0f4d";
      flake = false;
    };

    "therock-src-7-13-gfx1151-math-libs-libhipcxx-10b48ff4" = {
      url = "github:ROCm/libhipcxx/bc2b452b8c86ab65ba53e79e292b6c121e21a573";
      flake = false;
    };

    "therock-src-7-13-gfx1151-debug-tools-rocgdb-source-e3322990" = {
      url = "github:ROCm/rocgdb/c0a785c918a76c63328b774f244aca8f3d9a9dc7";
      flake = false;
    };

    "therock-src-7-13-gfx1151-iree-libs-iree-third-party-benchmark-0f3f8fcb" = {
      url = "github:google/benchmark/192ef10025eb2c4cdd392bc502f0c852196baa48";
      flake = false;
    };

    "therock-src-7-13-gfx1151-iree-libs-iree-third-party-flatcc-6e795d0f" = {
      url = "github:dvidelabs/flatcc/9362cd00f0007d8cbee7bff86e90fb4b6b227ff3";
      flake = false;
    };

    "therock-src-7-13-gfx1151-iree-libs-iree-third-party-llvm-project-053021c5" = {
      url = "github:iree-org/llvm-project/738ead2c739a6b1999db63a187185d00e534c747";
      flake = false;
    };

    "therock-src-7-13-gfx1151-iree-libs-iree-third-party-torch-mlir-decfc1a0" = {
      url = "github:iree-org/torch-mlir/172a8b4d5caddbb3af9045f7329dd4121b590cbf";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-libraries-projects-miopen-fin-2766eaa9" = {
      url = "github:ROCm/MIFin/06650bddfe40c47294b0414e4262691333b788dd";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-libraries-shared-tensile-hostlibrarytests-googletest-dd647abc" = {
      url = "github:google/googletest/e2239ee6043f73722e7aa812a459f54a28552929";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-experimental-python-perfxpert-opencode-2fa84e1d" = {
      url = "github:sst/opencode/a35b8a95c27d28e979a3826e1289d7ee87f40251";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-register-external-fmt-93ca61ec" = {
      url = "github:fmtlib/fmt/123913715afeb8a437e6388b4473fcc4753e1c9a";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-register-external-glog-da9d9e82" = {
      url = "github:google/glog/7b134a5c82c0c0b5698bb6bf7a835b230c5638e4";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-abseil-cpp-471579c4" = {
      url = "github:abseil/abseil-cpp/255c84dadd029fd8ad25c5efb5933e47beaa00c7";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-cereal-7f708e93" = {
      url = "github:jrmadsen/cereal/40a30defcb8874270a04836d316502b08904b2bc";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-doxygen-awesome-c-15f99d59" =
      {
        url = "github:jothepro/doxygen-awesome-css/df83fbf22cfff76b875c13d324baf584c74e96d0";
        flake = false;
      };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-elfio-cf38c296" = {
      url = "github:serge1/ELFIO/575bfdb12cd90fa8913660295103549f151d116a";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-filesystem-807165f4" = {
      url = "github:gulrak/filesystem/8a2edd6d92ed820521d42c94d179462bf06b5ed3";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-fmt-90ac0bf5" = {
      url = "github:fmtlib/fmt/407c905e45ad75fc29bf0f9bb7c5c2fd3475976f";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-googletest-0a626aae" = {
      url = "github:google/googletest/46db91ef6ffcc128b2d5f31118ae1108109e3400";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-gotcha-10fa2c98" = {
      url = "github:ROCm/GOTCHA/b944da10ff9b3364ef2e4b12e02cb2464e05dd48";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-json-a3f85fd2" = {
      url = "github:nlohmann/json/e41905fcb0938a7502d25ea5242c6b41396e21b0";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-perfetto-9d309359" = {
      url = "github:google/perfetto/eb5ef24c58d13cec289d733d03f0f3f0ed321b12";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-ptl-db721fa0" = {
      url = "github:jrmadsen/PTL/48df41625430d27ce43cf197fd467a8dda87cb45";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-pybind11-6da66437" = {
      url = "github:pybind/pybind11/914c06fb252b6cc3727d0eedab6736e88a3fcb01";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-sqlite-373e906e" = {
      url = "github:sqlite/sqlite/f5fb820c0f4781337faf02ed871be68d13a83d94";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-sdk-external-yaml-cpp-1bef3305" = {
      url = "github:jbeder/yaml-cpp/7b469b4220f96fb3d036cf68cd7bd30bd39e61d2";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-dyninst-5f477976" = {
      url = "github:ROCm/dyninst/da38f411d88540da46fbda1e811bcae47c1c8038";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-elfio-5047d340" = {
      url = "github:jrmadsen/ELFIO/d00cc32f8b1ed85d22309fac10576a1baf8a4736";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-filesystem-ded63cc0" =
      {
        url = "github:gulrak/filesystem/8a2edd6d92ed820521d42c94d179462bf06b5ed3";
        flake = false;
      };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-googletest-88801747" =
      {
        url = "github:google/googletest/6ec14dfd8c409d05fba94e18e3a02df35b874353";
        flake = false;
      };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-json-ef3d2b7e" = {
      url = "github:nlohmann/json/55f93686c01528224f448c19128836e7df245f72";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-onetbb-9159eae3" = {
      url = "github:uxlfoundation/oneTBB/f1862f38f83568d96e814e469ab61f88336cc595";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-papi-ae8ec169" = {
      url = "github:icl-utk-edu/papi/c27003e1642f1c151c9b18ef9e7610072b3c852d";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-perfetto-c27c4344" = {
      url = "github:google/perfetto/35b3d9845c2f4017865c4dc93fafcf6d202f1651";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-pybind11-92d9411d" = {
      url = "github:jrmadsen/pybind11/1a917f1852eb7819b671fc3fa862840f4c491a07";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-spdlog-1f6adb92" = {
      url = "github:gabime/spdlog/486b55554f11c9cccc913e11a87085b2a91f706f";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-sqlite-1519e496" = {
      url = "github:sqlite/sqlite/a5333afb9ad1aa473f8963b92caeaa955f47dc74";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-timemory-fb6426bf" = {
      url = "github:ROCm/timemory/6b967ed717a3263a91663a1662616acddade023f";
      flake = false;
    };

    "therock-src-7-13-gfx1151-third-party-sysdeps-linux-amd-mesa-mesa-fork-a692c85c" = {
      url = "github:ROCm/mesa-fork/9a0d5b03fd540cb2448c64bbda17dbf17ccb12bf";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-compute-src-vendored-pyyaml-b64e5974" =
      {
        url = "github:yaml/pyyaml/49790e73684bebad1df05ef8d828fa12f685bffb";
        flake = false;
      };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-plugin-perfetto-perfetto-4d7082cd" = {
      url = "github:google/perfetto/eb5ef24c58d13cec289d733d03f0f3f0ed321b12";
      flake = false;
    };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-examples-lulesh-extern-cd755d3c" =
      {
        url = "github:kokkos/kokkos/1a0c2ff6daf1068c65529ec04c2c046177847869";
        flake = false;
      };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-examples-openmp-extern-2e954ae7" =
      {
        url = "github:OpenMP-Validation-and-Verification/OpenMP_VV/2d06fc22ac62f418cb02c435f08b7e46bb8f3c5b";
        flake = false;
      };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-timemory-exte-811a2531" =
      {
        url = "github:ROCm/GOTCHA/6ef1232a0acc99f3340c2ca4c5d23890e9b8a459";
        flake = false;
      };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-timemory-exte-742cff1f" =
      {
        url = "github:libunwind/libunwind/24947191d61dda869e039e0414fe97e9f594acd5";
        flake = false;
      };

    "therock-src-7-13-gfx1151-rocm-systems-projects-rocprofiler-systems-external-timemory-exte-1cc6846c" =
      {
        url = "github:jrmadsen/yaml-cpp/1b50109f7bea60bd382d8ea7befce3d2bd67da5f";
        flake = false;
      };

    # END generated TheRock source inputs
  };

  outputs =
    {
      self,
      nixpkgs,
      ...
    }@inputs:
    let
      inherit (nixpkgs) lib;
      linuxSystems = [ "x86_64-linux" ];
      darwinSystems = [ "aarch64-darwin" ];
      systems = linuxSystems ++ darwinSystems;
      forAllSystems = lib.genAttrs systems;
      inputShortRev =
        input: input.shortRev or (if input ? rev then builtins.substring 0 7 input.rev else "unknown");
      inputVersion = prefix: input: "${prefix}-unstable-${inputShortRev input}";
      unstableInputVersion = input: "unstable-${inputShortRev input}";

      rocmTargetLib = import ./lib/rocm-targets.nix;
      therockTargetConfig = import ./pkgs/therock/targets.nix {
        inherit (rocmTargetLib) mkRocmTarget;
      };
      inherit (therockTargetConfig)
        defaultRocmTarget
        rocmTargets
        ;

      therockLib = import ./lib/therock.nix { inherit lib inputs; };
      inherit (therockLib)
        defaultTherockSources
        mkTherockRocmOverlay
        mkTherockPythonOverlay
        mkTherockOverlays
        ;

      therockOverlays = mkTherockOverlays {
        inherit rocmTargets;
        target = defaultRocmTarget;
      };

      therockRocmOverlay = therockOverlays.rocm;
      therockPythonOverlay = therockOverlays.python;
      therockVllmOverlay = therockOverlays.vllm;
      thunderboltIbverbsOverlay = inputs.thunderbolt-ibverbs.overlays.default;

      pkgsFor =
        system:
        import nixpkgs {
          inherit system;
          overlays = [ self.overlays.default ];
        };

      cudaPackagesFor =
        system:
        import nixpkgs {
          inherit system;
          overlays = [ self.overlays.default ];
          config = {
            allowUnfree = true;
            cudaSupport = true;
            cudaCapabilities = [ "8.9" ];
          };
        };

      perSystem = f: forAllSystems (system: f (pkgsFor system));

      benchmarkSuitesLib = import ./lib/benchmark-suites.nix { inherit lib; };

      mkBenchmarkSuites =
        pkgs:
        benchmarkSuitesLib.mkBenchmarkSuites {
          inherit pkgs self defaultRocmTarget;
          cudaPkgs =
            if pkgs.stdenv.isLinux then cudaPackagesFor pkgs.stdenv.hostPlatform.system else null;
        };

      mkLiveIsoConfiguration =
        {
          system ? "x86_64-linux",
          extraModules ? [ ],
          specialArgs ? { },
        }:
        nixpkgs.lib.nixosSystem {
          inherit system;
          specialArgs = {
            inherit inputs self;
          }
          // specialArgs;
          modules = [
            ./examples/configuration.nix
          ]
          ++ extraModules;
        };
    in
    {
      lib = {
        inherit
          defaultTherockSources
          mkLiveIsoConfiguration
          mkTherockOverlays
          mkTherockPythonOverlay
          mkTherockRocmOverlay
          ;
        benchmarks = import ./bench/lib.nix { inherit lib; };
        inherit (rocmTargetLib) mkRocmTarget;
        therockTargets = therockTargetConfig;
      };

      overlays = {
        default =
          final: prev:
          let
            thunderboltPackages = inputs.thunderbolt-ibverbs.packages.${prev.stdenv.hostPlatform.system};
            thunderboltCommonPackageAttrs = {
              thunderbolt-ibverbs-bench-tools = thunderboltPackages.bench-tools;
              thunderbolt-ibverbs-perftest = thunderboltPackages.perftest;
            };
          in
          thunderboltCommonPackageAttrs
          // lib.optionalAttrs prev.stdenv.isLinux (
            let
              ecPackages = prev.callPackage ./pkgs/ec-su-axb35.nix {
                ec-su-axb35-src = inputs.ec-su-axb35;
              };
              applyMasterSrc =
                attrName: pkg:
                pkg.overrideAttrs (old: {
                  pname = attrName;
                  version =
                    "master-" + (inputs.llama-cpp-master.shortRev or inputs.llama-cpp-master.rev or "unknown");
                  src = inputs.llama-cpp-master;
                  npmDeps = null;
                  nativeBuildInputs = prev.lib.filter (x: x.pname or "" != "npm-config-hook") (
                    old.nativeBuildInputs or [ ]
                  );
                  preConfigure = ''
                    prependToVar cmakeFlags "-DLLAMA_BUILD_COMMIT:STRING=${
                      inputs.llama-cpp-master.shortRev or inputs.llama-cpp-master.rev or "master"
                    }"
                  '';
                  cmakeFlags = (old.cmakeFlags or [ ]) ++ [
                    (prev.lib.cmakeBool "LLAMA_BUILD_UI" false)
                    (prev.lib.cmakeFeature "LLAMA_BUILD_NUMBER" "0")
                  ];
                });
              mkTargetedPackage =
                pname: pkg:
                pkg.overrideAttrs (_old: {
                  inherit pname;
                });
              mkLlamaCppRocmBase =
                rocmTarget:
                prev.llama-cpp.override {
                  rocmSupport = true;
                  rpcSupport = true;
                  inherit (final) rocmPackages;
                  inherit (rocmTarget) rocmGpuTargets;
                };
              llamaCppRocmTargetPackages = lib.listToAttrs (
                map (rocmTarget: {
                  name = "llama-cpp-rocm-${rocmTarget.packageSuffix}";
                  value = mkTargetedPackage "llama-cpp-rocm-${rocmTarget.packageSuffix}" (
                    mkLlamaCppRocmBase rocmTarget
                  );
                }) rocmTargets
              );
              llamaCppMasterRocmTargetPackages = lib.listToAttrs (
                map (rocmTarget: {
                  name = "llama-cpp-master-rocm-${rocmTarget.packageSuffix}";
                  value = applyMasterSrc "llama-cpp-master-rocm-${rocmTarget.packageSuffix}" (
                    mkLlamaCppRocmBase rocmTarget
                  );
                }) rocmTargets
              );
              llamaCppRocmBase = mkLlamaCppRocmBase defaultRocmTarget;
              llamaCppVulkanBase = prev.llama-cpp.override {
                vulkanSupport = true;
                rpcSupport = true;
              };
              llamaCppCudaBase = prev.llama-cpp.override {
                cudaSupport = true;
                rpcSupport = true;
              };
              ds4RocmTargets = builtins.filter (
                rocmTarget: builtins.hasAttr rocmTarget.packageSuffix defaultTherockSources.rocm.linux
              ) rocmTargets;
              ds4RocmTargetPackages = lib.listToAttrs (
                map (
                  rocmTarget:
                  let
                    s = rocmTarget.packageSuffix;
                  in
                  {
                    name = "ds4-rocm-${s}";
                    value = prev.callPackage ./pkgs/ds4-rocm {
                      src = inputs.ds4-hip;
                      rocmSdk = final."therock-rocm-${s}";
                      version = inputVersion "experimental" inputs.ds4-hip;
                      packageSuffix = s;
                      offloadArch = builtins.head rocmTarget.buildTargets;
                      hsaOverrideGfxVersion = rocmTarget.hsaOverride or null;
                    };
                  }
                ) ds4RocmTargets
              );
              thunderboltLinuxPackageAttrs = thunderboltCommonPackageAttrs // {
                inherit (thunderboltPackages)
                  linux-thunderbolt
                  linux-thunderbolt-dev
                  linux-thunderbolt-modules
                  rdma-core-usb4
                  thunderbolt-ibverbs
                  thunderbolt-ibverbs-linux-thunderbolt
                  ;
                rdma-core = thunderboltPackages.rdma-core-usb4;
              };
            in
            (thunderboltIbverbsOverlay final prev)
            // {
              # EC-SU_AXB35 packages
              ec-su-axb35 = ecPackages.kernelModule;
              ec-su-axb35-monitor = ecPackages.monitor;
              strix-halo-mes-firmware = prev.callPackage ./pkgs/strix-halo-mes-firmware.nix { };

              tokenizers-cpp = prev.callPackage ./pkgs/tokenizers-cpp { };

              xrt = prev.callPackage ./pkgs/xrt {
                src = inputs.xrt-src;
                version = inputVersion "2.21" inputs.xrt-src;
                xdnaSrc = inputs.xdna-driver-src;
                xdnaVersion = inputVersion "1.7" inputs.xdna-driver-src;
              };

              xrt-amdxdna = final.xrt.xdna;

              fastflowlm = prev.callPackage ./pkgs/fastflowlm {
                inherit (final) tokenizers-cpp xrt;
                src = inputs.fastflowlm;
              };

              ds4-rocm = ds4RocmTargetPackages."ds4-rocm-${defaultRocmTarget.packageSuffix}";

              # Generic ROCm llama.cpp build; target narrowing is explicit below.
              llama-cpp-rocm = llamaCppRocmBase;
              llama-cpp-vulkan = llamaCppVulkanBase;
              llama-cpp-cuda = llamaCppCudaBase;
              llama-cpp-master-rocm = applyMasterSrc "llama-cpp-master-rocm" llamaCppRocmBase;
              llama-cpp-master-vulkan = applyMasterSrc "llama-cpp-master-vulkan" llamaCppVulkanBase;
              llama-cpp-master-cuda = applyMasterSrc "llama-cpp-master-cuda" llamaCppCudaBase;
            }
            // ds4RocmTargetPackages
            // llamaCppRocmTargetPackages
            // llamaCppMasterRocmTargetPackages
            // thunderboltLinuxPackageAttrs
            // (therockRocmOverlay final prev)
            // (therockPythonOverlay final prev)
            // (therockVllmOverlay final prev)
          );

        thunderbolt-ibverbs = thunderboltIbverbsOverlay;
        therock-rocm = final: prev: lib.optionalAttrs prev.stdenv.isLinux (therockRocmOverlay final prev);
        therock-python =
          final: prev: lib.optionalAttrs prev.stdenv.isLinux (therockPythonOverlay final prev);
        therock-vllm =
          final: prev:
          lib.optionalAttrs prev.stdenv.isLinux (
            (therockRocmOverlay final prev)
            // (therockPythonOverlay final prev)
            // (therockVllmOverlay final prev)
          );
      };

      # NixOS modules
      nixosModules = {
        default = _: {
          imports = [
            inputs.thunderbolt-ibverbs.nixosModules.default
          ];
          nixpkgs.overlays = [
            self.overlays.default
          ];
        };
        rpc-server = import ./modules/rpc-server.nix;
        benchmark-executor = import ./modules/benchmark-executor.nix;
        benchmark-runner = import ./modules/benchmark-runner.nix;
        ec-su-axb35 = import ./modules/ec-su-axb35.nix;
        fastflowlm-server = import ./modules/fastflowlm-server.nix;
        ryzenadj = import ./modules/ryzenadj.nix;
        tuning = import ./modules/tuning.nix;
        thunderbolt-ibverbs = inputs.thunderbolt-ibverbs.nixosModules.default;
      };

      nixosConfigurations = {
        live-iso = mkLiveIsoConfiguration { };
      };

      darwinModules = {
        benchmark-executor = import ./modules/benchmark-executor.nix;
      };
    }
    // {
      benchmarks = perSystem mkBenchmarkSuites;

      packages = perSystem (
        pkgs:
        let
          s = defaultRocmTarget.packageSuffix;
          jacclPackage = pkgs.callPackage ./pkgs/jaccl (
            {
              inherit (inputs) mlx-src;
            }
            // lib.optionalAttrs pkgs.stdenv.isLinux {
              rdma-core = pkgs.rdma-core-usb4;
            }
          );
          genericPackages = {
            default = pkgs.llama-cpp;
            inherit (pkgs)
              llama-cpp
              thunderbolt-ibverbs-bench-tools
              thunderbolt-ibverbs-perftest
              ;
            jaccl = jacclPackage;
          };

          linuxPackages =
            let
              therockPackageNamesFor =
                rocmTarget:
                let
                  s = rocmTarget.packageSuffix;
                in
                [
                  "therock-amd-llvm-${s}"
                  "therock-rocm-${s}"
                  "therock-rocm-${s}-env"
                  "therock-rocm-${s}-rocshmem-env"
                  "therock-rocm-${s}-core"
                  "therock-rocm-${s}-cmake"
                  "therock-rocm-from-source-${s}"
                  "therock-rocm-from-source-${s}-configure"
                  "therock-rocm-source-${s}"
                  "therock-rocm-third-party-mirror-${s}"
                  "therock-python-${s}"
                  "therock-python-wheels-${s}"
                  "therock-amdsmi-${s}"
                  "torch-rocm-${s}"
                  "vllm-rocm-therock-${s}"
                ];
              therockPackageNames = lib.concatMap therockPackageNamesFor rocmTargets;
              requiredTherockPackageNames = therockPackageNamesFor defaultRocmTarget;
              missingRequiredTherockPackages = builtins.filter (
                name: !(builtins.hasAttr name pkgs)
              ) requiredTherockPackageNames;

              llamaCppTargetPackageNames = map (
                rocmTarget: "llama-cpp-rocm-${rocmTarget.packageSuffix}"
              ) rocmTargets;
              llamaCppMasterTargetPackageNames = map (
                rocmTarget: "llama-cpp-master-rocm-${rocmTarget.packageSuffix}"
              ) rocmTargets;
              llamaCppTargetPackages = lib.genAttrs (
                llamaCppTargetPackageNames ++ llamaCppMasterTargetPackageNames
              ) (name: pkgs.${name});
              ds4RocmPackageNames = map (rocmTarget: "ds4-rocm-${rocmTarget.packageSuffix}") rocmTargets;
              ds4RocmPackages = lib.genAttrs (builtins.filter (
                name: builtins.hasAttr name pkgs
              ) ds4RocmPackageNames) (name: pkgs.${name});
              cudaPkgs = cudaPackagesFor pkgs.stdenv.hostPlatform.system;
              mkMlxRocm =
                rocmTarget:
                let
                  buildTarget = builtins.head rocmTarget.buildTargets;
                in
                pkgs.python3Packages.callPackage ./pkgs/mlx/rocm.nix {
                  pname = "mlx-rocm-${rocmTarget.packageSuffix}";
                  rdma-core = pkgs.rdma-core-usb4;
                  rocmPackages = pkgs.therockRocmPackages.${buildTarget};
                  gfx = buildTarget;
                };
              mlxRocmTargets = builtins.filter (
                rocmTarget: builtins.hasAttr (builtins.head rocmTarget.buildTargets) pkgs.therockRocmPackages
              ) rocmTargets;
              mlxRocmTargetPackages = lib.listToAttrs (
                map (rocmTarget: {
                  name = "mlx-rocm-${rocmTarget.packageSuffix}";
                  value = mkMlxRocm rocmTarget;
                }) mlxRocmTargets
              );
              mlxRocm = mlxRocmTargetPackages."mlx-rocm-${s}";

              therockPackages =
                assert lib.assertMsg (missingRequiredTherockPackages == [ ])
                  "missing expected default TheRock package(s): ${lib.concatStringsSep ", " missingRequiredTherockPackages}";
                lib.genAttrs (builtins.filter (name: builtins.hasAttr name pkgs) therockPackageNames) (
                  name: pkgs.${name}
                );

            in
            {
              inherit (pkgs)
                ds4-rocm
                ec-su-axb35-monitor
                fastflowlm
                llama-cpp-rocm
                llama-cpp-vulkan
                llama-cpp-master-rocm
                llama-cpp-master-vulkan
                linux-thunderbolt
                linux-thunderbolt-dev
                linux-thunderbolt-modules
                rdma-core-usb4
                strix-halo-mes-firmware
                thunderbolt-ibverbs
                thunderbolt-ibverbs-linux-thunderbolt
                tokenizers-cpp
                xrt
                xrt-amdxdna
                ;
              inherit (cudaPkgs) llama-cpp-cuda llama-cpp-master-cuda;
              live-iso = self.nixosConfigurations.live-iso.config.system.build.isoImage;
              mlx = mlxRocm;
              mlx-rocm = mlxRocm;
            }
            // ds4RocmPackages
            // mlxRocmTargetPackages
            // llamaCppTargetPackages
            // therockPackages;
          darwinPackages =
            let
              mlxMetalBackend = pkgs.python3Packages.callPackage ./pkgs/mlx/metal.nix {
                inherit (inputs) mlx-src;
                pname = "mlx-metal";
                buildStage = 2;
              };
              mlxMetal = pkgs.python3Packages.callPackage ./pkgs/mlx/metal.nix {
                inherit (inputs) mlx-src;
                pname = "mlx";
                buildStage = 1;
                backendPackage = mlxMetalBackend;
              };
            in
            {
              ds4 = pkgs.callPackage ./pkgs/ds4 {
                src = inputs.ds4;
                version = unstableInputVersion inputs.ds4;
              };
              mlx = mlxMetal;
              mlx-metal = mlxMetalBackend;
            };
        in
        genericPackages
        // lib.optionalAttrs pkgs.stdenv.isLinux linuxPackages
        // lib.optionalAttrs pkgs.stdenv.isDarwin darwinPackages
      );

      apps = perSystem (
        pkgs:
        let
          system = pkgs.stdenv.hostPlatform.system;
          s = defaultRocmTarget.packageSuffix;
          mkApp =
            {
              name,
              packageName ? name,
              binary ? name,
              description,
            }:
            {
              type = "app";
              program = "${builtins.getAttr packageName pkgs}/bin/${binary}";
              meta.description = description;
            };
          mkDirectApp =
            {
              package,
              binary,
              description,
            }:
            {
              type = "app";
              program = "${package}/bin/${binary}";
              meta.description = description;
            };
          mkTargetLlamaApp =
            {
              name,
              package,
              hsaOverride ? null,
              binary,
              description,
            }:
            {
              type = "app";
              program = toString (
                pkgs.writeShellScript name ''
                  ${lib.optionalString (
                    hsaOverride != null
                  ) "export HSA_OVERRIDE_GFX_VERSION=${lib.escapeShellArg hsaOverride}"}
                  ${package}/bin/${binary} "$@"
                ''
              );
              meta.description = description;
            };

          mkTargetLlamaApps =
            rocmTarget:
            let
              suffix = rocmTarget.packageSuffix;
              package = builtins.getAttr "llama-cpp-rocm-${suffix}" pkgs;
              hsaOverride = rocmTarget.hsaOverride or null;
            in
            {
              "llama-cli-${suffix}" = mkTargetLlamaApp {
                name = "llama-cli-${suffix}";
                inherit package hsaOverride;
                binary = "llama-cli";
                description = "Run llama-cli with ROCm narrowed for ${rocmTarget.description}";
              };

              "llama-server-${suffix}" = mkTargetLlamaApp {
                name = "llama-server-${suffix}";
                inherit package hsaOverride;
                binary = "llama-server";
                description = "Run llama-server with ROCm narrowed for ${rocmTarget.description}";
              };
            };

          genericApps = {
            llama-cli = mkDirectApp {
              package = pkgs.llama-cpp;
              binary = "llama-cli";
              description = "Run llama-cli";
            };

            llama-server = mkDirectApp {
              package = pkgs.llama-cpp;
              binary = "llama-server";
              description = "Run llama-server";
            };
          };

          linuxApps = {
            llama-cli-rocm = mkDirectApp {
              package = pkgs.llama-cpp-rocm;
              binary = "llama-cli";
              description = "Run llama-cli with generic ROCm support";
            };

            llama-server-rocm = mkDirectApp {
              package = pkgs.llama-cpp-rocm;
              binary = "llama-server";
              description = "Run llama-server with generic ROCm support";
            };

            flm = mkDirectApp {
              package = pkgs.fastflowlm;
              binary = "flm";
              description = "Run the FastFlowLM CLI on AMD Ryzen AI NPUs";
            };

            live-iso-vm =
              let
                iso = self.packages.${system}.live-iso;
              in
              {
                type = "app";
                program = toString (
                  pkgs.writeShellScript "live-iso-vm" ''
                    set -euo pipefail
                    iso_file=$(echo ${iso}/iso/*.iso)
                    if [ ! -f "$iso_file" ]; then
                      echo "live ISO not found under ${iso}/iso" >&2
                      exit 1
                    fi
                    kvm_args=()
                    if [ -w /dev/kvm ]; then
                      kvm_args+=(-enable-kvm -cpu host)
                    fi
                    exec ${pkgs.qemu}/bin/qemu-system-x86_64 \
                      "''${kvm_args[@]}" \
                      -m ''${LIVE_ISO_MEM:-4G} \
                      -smp ''${LIVE_ISO_CPUS:-4} \
                      -cdrom "$iso_file" \
                      -boot d \
                      "$@"
                  ''
                );
                meta.description = "Boot the strix-halo live ISO in QEMU (override LIVE_ISO_MEM, LIVE_ISO_CPUS)";
              };
          }
          // (lib.foldl' lib.recursiveUpdate { } (map mkTargetLlamaApps rocmTargets))
          // lib.optionalAttrs (builtins.hasAttr "therock-rocm-${s}-env" pkgs) {
            "therock-rocm-${s}-env" = mkApp {
              name = "therock-rocm-${s}-env";
              description = "Run a command in the pinned TheRock ROCm ${s} environment";
            };
          }
          // lib.optionalAttrs (builtins.hasAttr "therock-rocm-${s}-rocshmem-env" pkgs) {
            "therock-rocm-${s}-rocshmem-env" = mkApp {
              name = "therock-rocm-${s}-rocshmem-env";
              description = "Run a command in the pinned TheRock ROCm ${s} rocSHMEM environment";
            };
          }
          // lib.optionalAttrs (builtins.hasAttr "therock-python-${s}" pkgs) {
            "therock-python-${s}" = mkApp {
              name = "therock-python-${s}";
              binary = "therock-python";
              description = "Run Python in the pinned TheRock ROCm/PyTorch wheel environment";
            };
            "therock-python-${s}-env" = mkApp {
              name = "therock-python-${s}-env";
              packageName = "therock-python-${s}";
              binary = "therock-python-env";
              description = "Run a command in the pinned TheRock ROCm/PyTorch wheel environment";
            };
          };

          darwinApps =
            let
              ds4Package = self.packages.${system}.ds4;
              mkDs4App = binary: description: {
                type = "app";
                program = "${ds4Package}/bin/${binary}";
                meta.description = description;
              };
            in
            {
              ds4 = mkDs4App "ds4" "Run DwarfStar 4 with Metal";
              ds4-server = mkDs4App "ds4-server" "Run the DwarfStar 4 HTTP server with Metal";
              ds4-bench = mkDs4App "ds4-bench" "Run the DwarfStar 4 benchmark with Metal";
              ds4-eval = mkDs4App "ds4-eval" "Run DwarfStar 4 eval with Metal";
              ds4-agent = mkDs4App "ds4-agent" "Run the DwarfStar 4 agent with Metal";
              ds4-download-model = mkDs4App "ds4-download-model" "Download DS4 DeepSeek V4 Flash GGUF weights";
            };
        in
        genericApps
        // lib.optionalAttrs pkgs.stdenv.isLinux linuxApps
        // lib.optionalAttrs pkgs.stdenv.isDarwin darwinApps
      );

      devShells = perSystem (pkgs: {
        default = pkgs.mkShell {
          packages =
            (with pkgs; [
              deadnix
              nix-fast-build
              nixfmt-tree
              statix
            ])
            ++ lib.optionals pkgs.stdenv.isLinux [
              (pkgs.python3.withPackages (
                ps: with ps; [
                  numpy
                  pandas
                  plotly
                ]
              ))
            ];
        };
      });

      formatter = perSystem (pkgs: pkgs.nixfmt-tree);

      checks = perSystem (
        pkgs:
        let
          system = pkgs.stdenv.hostPlatform.system;
          s = defaultRocmTarget.packageSuffix;
          therockPytorchPackage = "torch-rocm-${s}";
          benchmarkSet = self.benchmarks.${system};
          cpuBenchmark = benchmarkSet.bench-llama2-7b-llama-cpp-cpu-b512-fa1;
          cpuBenchmarkMetadata = builtins.toJSON cpuBenchmark.passthru.benchmark;

          benchmarkRunnerProfileConfig =
            (nixpkgs.lib.nixosSystem {
              system = "x86_64-linux";
              modules = [
                self.nixosModules.benchmark-runner
                (_: {
                  boot.kernelParams = [ "iommu=off" ];
                  benchmark.runners.ci = {
                    gpus = [
                      {
                        type = "amd";
                        arch = defaultRocmTarget.systemFeature;
                      }
                    ];
                    rdma.enable = true;
                    systemFeatures = [
                      defaultRocmTarget.systemFeature
                      "caller-feature"
                    ];
                    extraSandboxPaths = [ "/caller/device" ];
                  };
                })
              ];
            }).config;
          benchmarkRunnerProfileMetadata = builtins.toJSON {
            features = benchmarkRunnerProfileConfig.nix.settings.system-features;
            sandboxPaths = benchmarkRunnerProfileConfig.nix.settings.extra-sandbox-paths;
            tmpfilesRules = benchmarkRunnerProfileConfig.systemd.tmpfiles.rules;
            udevRules = benchmarkRunnerProfileConfig.services.udev.extraRules;
            deviceAclActivation =
              benchmarkRunnerProfileConfig.system.activationScripts.benchmark-runner-device-acls.text;
          };

          benchmarkExecutorConfig =
            (nixpkgs.lib.nixosSystem {
              system = "x86_64-linux";
              modules = [
                self.nixosModules.benchmark-executor
                (_: {
                  benchmark.executor = {
                    enable = true;
                    builders.gpu-builder = {
                      hostName = "gpu-builder.example";
                      sshUser = "builder";
                      systemFeatures = [ "rocm" ];
                      mandatoryFeatures = [ "benchmark" ];
                      gpus = [
                        {
                          type = "amd";
                          arch = "1151";
                        }
                      ];
                      publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBenchmarkExecutorCheck";
                    };
                  };
                })
              ];
            }).config;
          benchmarkExecutorMetadata = builtins.toJSON {
            buildMachines = benchmarkExecutorConfig.nix.buildMachines;
            knownHosts = benchmarkExecutorConfig.programs.ssh.knownHosts;
          };

          fastflowlmServerConfig =
            (nixpkgs.lib.nixosSystem {
              system = "x86_64-linux";
              modules = [
                self.nixosModules.default
                self.nixosModules.fastflowlm-server
                (_: {
                  boot.kernelParams = [ "iommu=pt" ];
                  services.fastflowlm-server = {
                    enable = true;
                    model = "llama3.2:1b";
                    host = "127.0.0.1";
                    port = 52625;
                    openFirewall = true;
                  };
                })
              ];
            }).config;
          fastflowlmServerMetadata = builtins.toJSON {
            execStart = fastflowlmServerConfig.systemd.services.fastflowlm-server.serviceConfig.ExecStart;
            udevRules = fastflowlmServerConfig.services.udev.extraRules;
            firewallPorts = fastflowlmServerConfig.networking.firewall.allowedTCPPorts;
          };

          mkSourceCheck =
            name: nativeBuildInputs: command:
            pkgs.runCommandLocal "ci-${name}"
              {
                inherit nativeBuildInputs;
                src = lib.cleanSource ./.;
              }
              ''
                export HOME="$TMPDIR"
                export XDG_CACHE_HOME="$TMPDIR/cache"
                cp -R "$src" source
                chmod -R u+w source
                cd source
                ${command}
                touch "$out"
              '';
        in
        {
          format = mkSourceCheck "format" [ pkgs.nixfmt-tree ] ''
            treefmt --tree-root . --walk filesystem --fail-on-change
          '';

          deadnix = mkSourceCheck "deadnix" [ pkgs.deadnix ] ''
            deadnix --fail .
          '';

          statix = mkSourceCheck "statix" [ pkgs.statix ] ''
            statix check .
          '';

          benchmark-metadata =
            pkgs.runCommandLocal "ci-benchmark-metadata"
              {
                nativeBuildInputs = [ pkgs.jq ];
              }
              ''
                cat > metadata.json <<'JSON'
                ${cpuBenchmarkMetadata}
                JSON

                jq -e '
                  .kind == "llama-cpp"
                  and .accelerator == "cpu"
                  and .requirements.systemFeatures == []
                  and .requirements.hostProfiles == []
                  and .requirements.sandboxPaths == []
                  and .model.path == "/models/llama-2-7b/llama-2-7b.Q4_K_M.gguf"
                  and .packages == [ "llama-cpp" ]
                  and .params.batch == 512
                  and .params.fa == 1
                  and (.command | length) >= 6
                ' metadata.json

                touch "$out"
              '';

          benchmark-executor =
            pkgs.runCommandLocal "ci-benchmark-executor"
              {
                nativeBuildInputs = [ pkgs.jq ];
              }
              ''
                cat > executor.json <<'JSON'
                ${benchmarkExecutorMetadata}
                JSON

                jq -e '
                  (.buildMachines | length) == 1
                  and .buildMachines[0].hostName == "gpu-builder.example"
                  and .buildMachines[0].sshUser == "builder"
                  and (.buildMachines[0].supportedFeatures | index("rocm") != null)
                  and (.buildMachines[0].supportedFeatures | index("gfx1151") != null)
                  and .buildMachines[0].mandatoryFeatures == [ "benchmark" ]
                  and .knownHosts."gpu-builder.example".publicKey == "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBenchmarkExecutorCheck"
                ' executor.json

                touch "$out"
              '';

          fastflowlm-server =
            pkgs.runCommandLocal "ci-fastflowlm-server"
              {
                nativeBuildInputs = [ pkgs.jq ];
              }
              ''
                cat > server.json <<'JSON'
                ${fastflowlmServerMetadata}
                JSON

                jq -e '
                  (.execStart | contains("flm serve"))
                  and (.execStart | contains("--host 127.0.0.1"))
                  and (.execStart | contains("--port 52625"))
                  and (.execStart | contains("llama3.2:1b"))
                  and (.udevRules | contains("SUBSYSTEM==\"accel\""))
                  and (.firewallPorts | index(52625) != null)
                ' server.json

                touch "$out"
              '';

          package-llama-cpp = pkgs.llama-cpp;
          package-jaccl = self.packages.${system}.jaccl;
        }
        // lib.optionalAttrs pkgs.stdenv.isLinux (
          let
            fastflowlmBenchmark = benchmarkSet.bench-llama3-2-1b-fastflowlm-medium;
            fastflowlmBenchmarkMetadata = builtins.toJSON fastflowlmBenchmark.passthru.benchmark;
            ds4Benchmark = benchmarkSet.bench-deepseek-v4-flash-ds4-rocm-gfx1151-smoke;
            ds4BenchmarkMetadata = builtins.toJSON ds4Benchmark.passthru.benchmark;
            mlxRocmSmokeBenchmark = benchmarkSet.bench-mlx-rocm-gfx1151-gemm-smoke;
            mlxRocmSmokeBenchmarkMetadata = builtins.toJSON mlxRocmSmokeBenchmark.passthru.benchmark;
            vllmThroughputBenchmark = benchmarkSet.bench-qwen3-0-6b-vllm-rocm-gfx1151-throughput-smoke;
            vllmThroughputBenchmarkMetadata = builtins.toJSON (
              removeAttrs vllmThroughputBenchmark.passthru.benchmark [ "command" ]
            );
            vllmLatencyBenchmark = benchmarkSet.bench-qwen3-0-6b-vllm-rocm-gfx1151-latency-smoke;
            vllmLatencyBenchmarkMetadata = builtins.toJSON (
              removeAttrs vllmLatencyBenchmark.passthru.benchmark [ "command" ]
            );
            cudaSmokeBenchmark = benchmarkSet.bench-cuda-rtx4090-llama-cpp-master-device-smoke;
            cudaSmokeBenchmarkMetadata = builtins.toJSON (
              removeAttrs cudaSmokeBenchmark.passthru.benchmark [ "command" ]
            );
          in
          {
            benchmark-runner-profiles =
              pkgs.runCommandLocal "ci-benchmark-runner-profiles"
                {
                  nativeBuildInputs = [ pkgs.jq ];
                }
                ''
                  cat > profile.json <<'JSON'
                  ${benchmarkRunnerProfileMetadata}
                  JSON

                  jq -e '
                    (.features | index("${defaultRocmTarget.systemFeature}") != null)
                    and (.features | index("caller-feature") != null)
                    and (.features | index("rdma-usb4") != null)
                    and (.sandboxPaths | index("/models") != null)
                    and (.sandboxPaths | index("/dev/dri?") != null)
                    and (.sandboxPaths | index("/dev/kfd?") != null)
                    and (.sandboxPaths | index("/sys/class/hwmon?") != null)
                    and (.sandboxPaths | index("/sys/class/net?") != null)
                    and (.sandboxPaths | index("/sys/class/scsi_host?") != null)
                    and (.sandboxPaths | index("/sys/bus/pci/devices?") != null)
                    and (.sandboxPaths | index("/dev/infiniband?") != null)
                    and (.sandboxPaths | index("/dev/accel?") == null)
                    and (.sandboxPaths | index("/caller/device") != null)
                    and (.tmpfilesRules | index("d /models 0755 root root -") != null)
                    and (.tmpfilesRules | map(test("^z /dev/")) | any | not)
                    and (.udevRules | contains("GROUP:=\"nixbld\"") | not)
                    and (.udevRules | contains("MODE:=\"0660\"") | not)
                    and (.udevRules | contains("KERNEL==\"kfd\", RUN+="))
                    and (.udevRules | contains("setfacl -m g:nixbld:rw /dev/$kernel"))
                    and (.udevRules | contains("SUBSYSTEM==\"drm\", KERNEL==\"card*\", RUN+="))
                    and (.udevRules | contains("setfacl -m g:nixbld:rw /dev/dri/$kernel"))
                    and (.udevRules | contains("SUBSYSTEM==\"drm\", KERNEL==\"renderD*\", RUN+="))
                    and (.udevRules | contains("SUBSYSTEM==\"infiniband_verbs\", RUN+="))
                    and (.udevRules | contains("setfacl -m g:nixbld:rw /dev/infiniband/$kernel"))
                    and (.deviceAclActivation | contains("/dev/kfd"))
                    and (.deviceAclActivation | contains("/dev/dri/card*"))
                    and (.deviceAclActivation | contains("/dev/dri/renderD*"))
                    and (.deviceAclActivation | contains("/dev/infiniband/*"))
                    and (.deviceAclActivation | contains("setfacl -m g:nixbld:rw"))
                    and (.deviceAclActivation | contains("chgrp") | not)
                    and (.deviceAclActivation | contains("chmod") | not)
                  ' profile.json

                  touch "$out"
                '';

            fastflowlm-benchmark-metadata =
              pkgs.runCommandLocal "ci-fastflowlm-benchmark-metadata"
                {
                  nativeBuildInputs = [ pkgs.jq ];
                }
                ''
                  cat > metadata.json <<'JSON'
                  ${fastflowlmBenchmarkMetadata}
                  JSON

                  jq -e '
                    .kind == "fastflowlm"
                    and .accelerator == "npu"
                    and .requirements.systemFeatures == [ "xdna2" ]
                    and .requirements.hostProfiles == [ "linux-amd-xdna" ]
                    and (.requirements.sandboxPaths | index("/dev/accel") != null)
                    and .model.tag == "llama3.2:1b"
                    and .env.FLM_MODEL_PATH == "/models/flm"
                    and .packages == [ "fastflowlm" ]
                  ' metadata.json

                  touch "$out"
                '';

            ds4-benchmark-metadata =
              pkgs.runCommandLocal "ci-ds4-benchmark-metadata"
                {
                  nativeBuildInputs = [ pkgs.jq ];
                }
                ''
                  cat > metadata.json <<'JSON'
                  ${ds4BenchmarkMetadata}
                  JSON

                  jq -e '
                    .kind == "ds4"
                    and .accelerator == "rocm"
                    and .backend == "hip"
                    and .requirements.systemFeatures == [ "gfx1151" ]
                    and .requirements.hostProfiles == [ "linux-amd-kfd" ]
                    and (.requirements.sandboxPaths | index("/dev/kfd") != null)
                    and (.requirements.sandboxPaths | index("/dev/dri") != null)
                    and (.requirements.sandboxPaths | index("/models/ds4") != null)
                    and .model.path == "/models/ds4/ds4flash.gguf"
                    and .packages == [ "ds4-rocm-gfx1151" ]
                    and .params.ctxStart == 128
                    and .params.ctxMax == 256
                    and .params.genTokens == 8
                  ' metadata.json

                  touch "$out"
                '';

            mlx-rocm-gemm-smoke-metadata =
              pkgs.runCommandLocal "ci-mlx-rocm-gemm-smoke-metadata"
                {
                  nativeBuildInputs = [ pkgs.jq ];
                }
                ''
                  cat > metadata.json <<'JSON'
                  ${mlxRocmSmokeBenchmarkMetadata}
                  JSON

                  jq -e '
                    .kind == "mlx-gpu-smoke"
                    and .suite == "mlx"
                    and .accelerator == "rocm"
                    and .backend == "rocm"
                    and .scenario == "gemm-smoke"
                    and .requirements.systemFeatures == [ "gfx1151" ]
                    and .requirements.hostProfiles == [ "linux-amd-kfd" ]
                    and (.requirements.sandboxPaths | index("/dev/kfd") != null)
                    and (.requirements.sandboxPaths | index("/dev/dri") != null)
                    and .packages == [ "mlx-rocm-gfx1151" ]
                    and .params.op == "matmul"
                    and .params.n == 256
                    and .target.packageSuffix == "gfx1151"
                    and .tool.packageRole == "mlx-rocm-gfx1151"
                    and .tool.executable == "python"
                  ' metadata.json

                  touch "$out"
                '';

            cuda-smoke-benchmark-metadata =
              pkgs.runCommandLocal "ci-cuda-smoke-benchmark-metadata"
                {
                  nativeBuildInputs = [ pkgs.jq ];
                }
                ''
                  cat > metadata.json <<'JSON'
                  ${cudaSmokeBenchmarkMetadata}
                  JSON

                  jq -e '
                    .kind == "cuda-smoke"
                    and .accelerator == "cuda"
                    and .scenario == "device-smoke"
                    and .requirements.systemFeatures == [ "cuda-smoke" ]
                    and .requirements.hostProfiles == [ "linux-nvidia-cuda" ]
                    and (.requirements.sandboxPaths | index("/dev/nvidia0") != null)
                    and (.requirements.sandboxPaths | index("/run/opengl-driver") == null)
                    and (.env.LD_LIBRARY_PATH | test("nvidia-x11-[^/]+/lib$"))
                    and .target.deviceClass == "rtx4090"
                    and .target.arch == "sm_89"
                    and .packages == [ "llama-cpp-master-cuda", "nvidia-x11" ]
                    and .tool.executable == "llama-bench --list-devices"
                  ' metadata.json

                  touch "$out"
                '';

            vllm-benchmark-metadata =
              pkgs.runCommandLocal "ci-vllm-benchmark-metadata"
                {
                  nativeBuildInputs = [ pkgs.jq ];
                }
                ''
                  cat > throughput.json <<'JSON'
                  ${vllmThroughputBenchmarkMetadata}
                  JSON

                  cat > latency.json <<'JSON'
                  ${vllmLatencyBenchmarkMetadata}
                  JSON

                  jq -e '
                    .kind == "vllm"
                    and .mode == "throughput"
                    and .accelerator == "rocm"
                    and .requirements.systemFeatures == [ "gfx1151" ]
                    and .requirements.hostProfiles == [ "linux-amd-kfd" ]
                    and (.requirements.sandboxPaths | index("/dev/kfd") != null)
                    and (.requirements.sandboxPaths | index("/sys/class/hwmon") != null)
                    and (.requirements.sandboxPaths | index("/sys/class/net") != null)
                    and (.requirements.sandboxPaths | index("/sys/class/scsi_host") != null)
                    and (.requirements.sandboxPaths | index("/sys/bus/pci/devices") != null)
                    and (.requirements.sandboxPaths | index("/models") != null)
                    and .model.id == "Qwen/Qwen3-0.6B"
                    and .env.HF_HOME == "/models/.cache/huggingface"
                    and .env.HF_HUB_OFFLINE == "1"
                    and .env.VK_DRIVER_FILES == ""
                    and .env.VK_ICD_FILENAMES == ""
                    and .env.OCL_ICD_VENDORS == "/var/empty"
                    and .packages == [ "vllm" ]
                    and .params.inputLen == 128
                    and .params.outputLen == 32
                    and .params.numPrompts == 8
                    and .tool.executable == "vllm bench throughput"
                  ' throughput.json

                  jq -e '
                    .kind == "vllm"
                    and .mode == "latency"
                    and .accelerator == "rocm"
                    and .requirements.systemFeatures == [ "gfx1151" ]
                    and .requirements.hostProfiles == [ "linux-amd-kfd" ]
                    and .model.id == "Qwen/Qwen3-0.6B"
                    and .packages == [ "vllm" ]
                    and .params.batchSize == 1
                    and .params.numItersWarmup == 1
                    and .params.numIters == 3
                    and .tool.executable == "vllm bench latency"
                  ' latency.json

                  touch "$out"
                '';

            "package-llama-cpp-rocm-${s}" = pkgs."llama-cpp-rocm-${s}";
            "package-ds4-rocm-${s}" = pkgs."ds4-rocm-${s}";
            package-mlx-rocm = self.packages.${system}.mlx-rocm;
            package-mlx-rocm-gfx1151 = self.packages.${system}.mlx-rocm-gfx1151;
            "package-vllm-rocm-therock-${s}" = pkgs."vllm-rocm-therock-${s}";
            package-fastflowlm = pkgs.fastflowlm;
            package-strix-halo-mes-firmware = pkgs.strix-halo-mes-firmware;
            "therock-pytorch-${s}" = pkgs.${therockPytorchPackage};

            llama-cpp-vulkan-benchmark-icd-pin =
              let
                vulkanBench = benchmarkSet.bench-llama2-7b-llama-cpp-vulkan-b1-fa1;
                vulkanMetadata = builtins.toJSON vulkanBench.passthru.benchmark;
              in
              pkgs.runCommandLocal "ci-llama-cpp-vulkan-benchmark-icd-pin"
                {
                  nativeBuildInputs = [ pkgs.jq ];
                }
                ''
                  cat > metadata.json <<'JSON'
                  ${vulkanMetadata}
                  JSON

                  jq -e '
                    (.env.VK_DRIVER_FILES | test("/share/vulkan/icd.d/radeon_icd\\.x86_64\\.json$"))
                  ' metadata.json

                  touch "$out"
                '';

            live-iso-boot =
              let
                iso = self.packages.${system}.live-iso;
              in
              pkgs.runCommand "ci-live-iso-boot"
                {
                  nativeBuildInputs = [
                    pkgs.qemu_test
                    pkgs.expect
                  ];
                  requiredSystemFeatures = [
                    "kvm"
                    "nixos-test"
                  ];
                  meta.timeout = 900;
                }
                ''
                  set -euo pipefail
                  iso_file=$(echo ${iso}/iso/*.iso)
                  if [ ! -f "$iso_file" ]; then
                    echo "ISO not found at $iso_file" >&2
                    exit 1
                  fi

                  echo "Booting $iso_file in QEMU..."

                  ISO_FILE=$iso_file expect <<'EXPECT'
                    set timeout 300
                    spawn qemu-system-x86_64 \
                      -enable-kvm \
                      -cpu host \
                      -m 2G \
                      -smp 2 \
                      -cdrom $env(ISO_FILE) \
                      -boot d \
                      -nographic \
                      -no-reboot
                    expect {
                      "strix-halo-live login: nixos (automatic login)" {
                        send_user "\n>>> auto-login OK\n"
                      }
                      timeout { send_user "\n!!! TIMEOUT waiting for login prompt\n"; exit 1 }
                      eof { send_user "\n!!! VM exited before login prompt\n"; exit 1 }
                    }
                    expect {
                      "strix-halo-live:" {
                        send_user "\n>>> shell prompt OK\n"
                      }
                      timeout { send_user "\n!!! TIMEOUT waiting for shell prompt\n"; exit 1 }
                    }
                    send "command -v llama-cli && command -v flm && grep -F amd_iommu=pt /proc/cmdline && echo BOOTOK\r"
                    expect {
                      "BOOTOK" { send_user "\n>>> sanity checks OK\n"; exit 0 }
                      timeout { send_user "\n!!! TIMEOUT during sanity checks\n"; exit 1 }
                    }
                  EXPECT

                  touch "$out"
                '';
          }
        )
        // lib.optionalAttrs pkgs.stdenv.isDarwin (
          let
            ds4MetalBenchmark = benchmarkSet.bench-deepseek-v4-flash-ds4-metal-smoke;
            ds4MetalBenchmarkMetadata = builtins.toJSON ds4MetalBenchmark.passthru.benchmark;
            mlxMetalSmokeBenchmark = benchmarkSet.bench-mlx-metal-gemm-smoke;
            mlxMetalSmokeBenchmarkMetadata = builtins.toJSON mlxMetalSmokeBenchmark.passthru.benchmark;
          in
          {
            package-mlx = self.packages.${system}.mlx;
            package-mlx-metal = self.packages.${system}.mlx-metal;
            ds4-metal-benchmark-metadata =
              pkgs.runCommandLocal "ci-ds4-metal-benchmark-metadata"
                {
                  nativeBuildInputs = [ pkgs.jq ];
                }
                ''
                  cat > metadata.json <<'JSON'
                  ${ds4MetalBenchmarkMetadata}
                  JSON

                  jq -e '
                    .kind == "ds4"
                    and .accelerator == "metal"
                    and .backend == "metal"
                    and .requirements.systemFeatures == [ "metal", "benchmark" ]
                    and .requirements.hostProfiles == [ "darwin-metal" ]
                    and (.requirements.sandboxPaths | index("/Users/Shared/models/ds4") != null)
                    and .model.path == "/Users/Shared/models/ds4/ds4flash.gguf"
                    and .packages == [ "ds4" ]
                    and .env.DS4_METAL_NO_RESIDENCY == "1"
                    and .env.DS4_METAL_NO_MODEL_WARMUP == "1"
                    and .target.packageSuffix == "metal"
                    and .tool.packageRole == "ds4"
                    and .params.ctxStart == 128
                    and .params.ctxMax == 256
                    and .params.genTokens == 8
                  ' metadata.json

                  touch "$out"
                '';

            mlx-metal-gemm-smoke-metadata =
              pkgs.runCommandLocal "ci-mlx-metal-gemm-smoke-metadata"
                {
                  nativeBuildInputs = [ pkgs.jq ];
                }
                ''
                  cat > metadata.json <<'JSON'
                  ${mlxMetalSmokeBenchmarkMetadata}
                  JSON

                  jq -e '
                    .kind == "mlx-gpu-smoke"
                    and .suite == "mlx"
                    and .accelerator == "metal"
                    and .backend == "metal"
                    and .scenario == "gemm-smoke"
                    and .requirements.systemFeatures == [ "metal", "benchmark" ]
                    and .requirements.hostProfiles == [ "darwin-metal" ]
                    and .requirements.sandboxPaths == []
                    and .packages == [ "mlx" ]
                    and .params.op == "matmul"
                    and .params.n == 256
                    and .target.packageSuffix == "metal"
                    and .tool.packageRole == "mlx"
                    and .tool.executable == "python"
                  ' metadata.json

                  touch "$out"
                '';
          }
        )
      );

      hydraJobs = perSystem (
        pkgs:
        let
          system = pkgs.stdenv.hostPlatform.system;
          isSourceCheckSystem = system == "x86_64-linux";

          mkAggregate =
            aggregateName: jobs:
            pkgs.linkFarm "nix-strix-halo-${aggregateName}" (
              lib.mapAttrsToList (name: path: {
                inherit name path;
              }) jobs
            );

          prQuickJobs = lib.optionalAttrs isSourceCheckSystem self.checks.${system};
          prQuick = mkAggregate "pr-quick" prQuickJobs;

          afterPrQuick =
            name: path:
            pkgs.linkFarm "nix-strix-halo-pr-full-${name}" (
              lib.optionals isSourceCheckSystem [
                {
                  name = "pr-quick";
                  path = prQuick;
                }
              ]
              ++ [
                {
                  inherit name path;
                }
              ]
            );

          prFullJobs = {
            default = afterPrQuick "default" self.packages.${system}.default;
            jaccl = afterPrQuick "jaccl" self.packages.${system}.jaccl;
          }
          // lib.optionalAttrs (system == "aarch64-darwin") {
            ds4 = afterPrQuick "ds4" self.packages.${system}.ds4;
            mlx = afterPrQuick "mlx" self.packages.${system}.mlx;
            mlx-metal = afterPrQuick "mlx-metal" self.packages.${system}.mlx-metal;
            mlx-metal-gemm-smoke =
              afterPrQuick "mlx-metal-gemm-smoke"
                self.benchmarks.${system}.bench-mlx-metal-gemm-smoke;
          }
          // lib.optionalAttrs (system == "x86_64-linux") {
            mlx-rocm = afterPrQuick "mlx-rocm" self.packages.${system}.mlx-rocm;
            mlx-rocm-gfx1151 = afterPrQuick "mlx-rocm-gfx1151" self.packages.${system}.mlx-rocm-gfx1151;
            mlx-rocm-gemm-smoke =
              afterPrQuick "mlx-rocm-gemm-smoke"
                self.benchmarks.${system}.bench-mlx-rocm-gfx1151-gemm-smoke;
            live-iso = afterPrQuick "live-iso" self.packages.${system}.live-iso;
            vllm =
              afterPrQuick "vllm"
                self.packages.${system}."vllm-rocm-therock-${defaultRocmTarget.packageSuffix}";
            vllm-throughput-smoke =
              afterPrQuick "vllm-throughput-smoke"
                self.benchmarks.${system}.bench-qwen3-0-6b-vllm-rocm-gfx1151-throughput-smoke;
            cuda-smoke =
              afterPrQuick "cuda-smoke"
                self.benchmarks.${system}.bench-cuda-rtx4090-llama-cpp-master-device-smoke;
          };
        in
        lib.optionalAttrs isSourceCheckSystem {
          "pr-quick" = prQuickJobs // {
            all = prQuick;
          };
        }
        // {
          "pr-full" = prFullJobs // {
            all = mkAggregate "pr-full" prFullJobs;
          };
        }
        // lib.optionalAttrs (system == "x86_64-linux") {
          # Re-export the raw ISO derivation alongside the linkFarm-wrapped
          # `pr-full.live-iso`. The linkFarm wrapper gates the build on
          # `pr-quick` but loses the underlying ISO's
          # `nix-support/hydra-build-products` file, so Hydra's
          # download-by-type/file/iso UI cannot find the iso through it.
          # The raw job below preserves the build product so the latest
          # successful build is directly downloadable.
          live-iso = self.packages.${system}.live-iso;
        }
      );
    };
}
